### create
POST http://localhost:7000/api/contacts/2/addresses
Content-Type: application/json

{
	"street" : "Jalan Pulau Roon No. 12B",
	"city" : "Denpasar",
	"province" : "Bali",
	"country" : "Indonesia",
	"postalCode" : "80113"
}

### get
GET  http://localhost:7000/api/contacts/2/addresses/1
Content-Type: application/json

### update
PUT http://localhost:7000/api/contacts/2/addresses/1
Content-Type: application/json

{
	"street" : "Jalan Pulau Roon No. 12",
	"city" : "Denpasar",
	"province" : "Bali",
	"country" : "Indonesia",
	"postalCode" : "80113"
}

### delete
DELETE  http://localhost:7000/api/contacts/2/addresses/3
Content-Type: application/json

### list
GET  http://localhost:7000/api/contacts/2/addresses
Content-Type: application/json