### check server ok
GET http://localhost:6000/

### check server ok
GET http://localhost:6000/api/

### register
POST http://localhost:7000/api/register/
Content-Type: application/json

{
	"name": "admin",
	"username": "admin",
	"email" : "admin@gmail.com",
	"password": "811899"
}

### login
POST http://localhost:7000/api/login/
Content-Type: application/json

{
	"username" : "mastika",
	"password": "811899"
}

### logout
POST http://localhost:7000/api/logout/
Content-Type: application/json


### get list user
GET http://localhost:7000/api/users

### get user
GET http://localhost:7000/api/users/current

### isAuthenticated
GET http://localhost:7000/api/isAuthenticated/

### isEmailExist
GET http://localhost:6000/api/user/isEmailExist/m4stika@gmail.com


### isUserExist
GET http://localhost:8001/api/user/isUserExist/mastika