/* import { AccountLevel, GroupAccount } from "@prisma/client";

// export const CoA: Omit<ChartOfAccount,"code" | "isBalanceSheetAccount" | "accountNo" | "showInReport">[] = [
export const CoA = [
	// Level 1
	{ id: "000000", description: "PERKIRAAN", accountLevel: AccountLevel.ROOT, levelAcc:0, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: null },
	{ id: "100000", description: "ASSET", levelAcc:1, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "000000", accountLevel: AccountLevel.GROUP, showInReport: true  },
	{ id: "200000", description: "LIABILITAS", levelAcc:1, typeAcc: GroupAccount.GROUP, isDebit: false, parentId: "000000", accountLevel: AccountLevel.GROUP, showInReport: true },
  { id: "300000", description: "EKUITAS", levelAcc:1, typeAcc: GroupAccount.GROUP, isDebit: false, parentId: "000000", accountLevel: AccountLevel.GROUP, showInReport: true },
	//{ id: "400000", description: "AKUN PERANTARA", levelAcc:1, typeAcc: GroupAccount.GROUP, isDebit: false, parentId: "000000", accountLevel: AccountLevel.GROUP, showInReport: true },
  { id: "400000", description: "PENDAPATAN OPERASI", levelAcc:1, typeAcc: GroupAccount.GROUP, isDebit: false, parentId: "000000", accountLevel: AccountLevel.GROUP, showInReport: true },
  { id: "500000", description: "BEBAN LANGSUNG", levelAcc:1, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "000000", accountLevel: AccountLevel.GROUP, showInReport: true },
  { id: "600000", description: "BEBAN USAHA", levelAcc:1, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "000000", accountLevel: AccountLevel.GROUP, showInReport: true },
  { id: "700000", description: "PENDAPATAN DAN BEBAN DILUAR OPERASI", levelAcc:1, typeAcc: GroupAccount.GROUP, isDebit: false, parentId: "000000", accountLevel: AccountLevel.GROUP, showInReport: true },
  { id: "800000", description: "PAJAK PENGHASILAN BADAN", levelAcc:1, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "000000", accountLevel: AccountLevel.GROUP, showInReport: true },

	// Level 2
	{ id: "110000", description: "ASSET LANCAR", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "100000", accountLevel: AccountLevel.SUB_GROUP, showInReport: true },
	{ id: "120000", description: "ASET TIDAK LANCAR", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "100000", accountLevel: AccountLevel.SUB_GROUP, showInReport: true },
	{ id: "190000", description: "AKUN PERANTARA", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "100000", accountLevel: AccountLevel.SUB_GROUP},
	{ id: "210000", description: "LIABILITAS JANGKA PENDEK", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: false, parentId: "200000", accountLevel: AccountLevel.SUB_GROUP, showInReport: true },
	{ id: "220000", description: "LIABILITAS JANGKA PANJANG", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: false, parentId: "200000" , accountLevel: AccountLevel.SUB_GROUP, showInReport: true },
	{ id: "310000", description: "MODAL", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: false, parentId: "300000" , accountLevel: AccountLevel.SUB_GROUP },
	{ id: "320000", description: "LABA", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: false, parentId: "300000" , accountLevel: AccountLevel.SUB_GROUP },
	{ id: "330000", description: "IKHTISAR LABA-RUGI", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: false, parentId: "300000" , accountLevel: AccountLevel.SUB_GROUP },
	// { id: "410000", description: "PENDAPATAN", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: false, parentId: "400000" , accountLevel: AccountLevel.SUB_GROUP },
	{ id: "510000", description: "BEBAN JASA TENAGA ALIH DAYA", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "500000" , accountLevel: AccountLevel.SUB_GROUP, showInReport: true },
	{ id: "520000", description: "BEBAN JASA KONSTRUKSI DAN PEMELIHARAAN KELISTRIKAN", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "500000" , accountLevel: AccountLevel.SUB_GROUP, showInReport: true },
	{ id: "530000", description: "BEBAN JASA LAINNYA", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "500000" , accountLevel: AccountLevel.SUB_GROUP, showInReport: true },
	{ id: "580000", description: "HARGA POKOK PENJUALAN", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "500000" , accountLevel: AccountLevel.SUB_GROUP, showInReport: true },
	{ id: "610000", description: "BEBAN KEPEGAWAIAN", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "600000" , accountLevel: AccountLevel.SUB_GROUP, showInReport: true },
	{ id: "620000", description: "BEBAN ADMINISTRASI DAN UMUM", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "600000" , accountLevel: AccountLevel.SUB_GROUP, showInReport: true },
	{ id: "630000", description: "BEBAN PEMELIHARAAN", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "600000" , accountLevel: AccountLevel.SUB_GROUP, showInReport: true },
	{ id: "640000", description: "BEBAN PENYUSUTAN ASET TETAP DAN AMORTISASI", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "600000" , accountLevel: AccountLevel.SUB_GROUP, showInReport: true },
	{ id: "710000", description: "PENDAPATAN DILUAR OPERASI", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: false, parentId: "700000" , accountLevel: AccountLevel.SUB_GROUP, showInReport: true },
	{ id: "720000", description: "BEBAN DILUAR OPERASI", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: false, parentId: "700000" , accountLevel: AccountLevel.SUB_GROUP, showInReport: true },
	// { id: "810000", description: "PAJAK PENGHASILAN BADAN", levelAcc:2, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "800000" , accountLevel: AccountLevel.SUB_GROUP },

	// Level 3
	{ id: "111000", description: "KAS DAN SETARA KAS", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "110000", accountLevel: AccountLevel.CLUSTER, showInReport: true, cashAccount: true },
	{ id: "112000", description: "PIUTANG", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "110000", accountLevel: AccountLevel.CLUSTER, showInReport: true },
	{ id: "113000", description: "PERSEDIAAN", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "110000", accountLevel: AccountLevel.CLUSTER, showInReport: true },
	{ id: "114000", description: "UANG MUKA DAN BEBAN DIBAYAR DIMUKA", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "110000", accountLevel: AccountLevel.CLUSTER, showInReport: true },
	{ id: "115000", description: "UANG MUKA PAJAK", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "110000", accountLevel: AccountLevel.CLUSTER, showInReport: true },
	{ id: "121000", description: "ASSET TETAP", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "120000", accountLevel: AccountLevel.CLUSTER },
	{ id: "122000", description: "UANG MUKA DAN BEBAN DIBAYAR DIMUKA", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "120000", accountLevel: AccountLevel.CLUSTER },
	{ id: "123000", description: "INVESTASI JANGKA PANJANG", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "120000", accountLevel: AccountLevel.CLUSTER },
	{ id: "124000", description: "AKTIVA LAIN LAIN", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "120000", accountLevel: AccountLevel.CLUSTER, showInReport: true },
	{ id: "211000", description: "UTANG USAHA", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: false, parentId: "210000", accountLevel: AccountLevel.CLUSTER, showInReport: true },
	{ id: "212000", description: "UTANG PINJAMAN", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: false, parentId: "210000", accountLevel: AccountLevel.CLUSTER, showInReport: true},
	{ id: "213000", description: "UTANG PAJAK", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: false, parentId: "210000", accountLevel: AccountLevel.CLUSTER, showInReport: true },
	{ id: "214000", description: "UTANG LANCAR LAINNYA", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: false, parentId: "210000", accountLevel: AccountLevel.CLUSTER },
	{ id: "511000", description: "BEBAN TENAGA KERJA", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "510000", accountLevel: AccountLevel.CLUSTER },
	{ id: "512000", description: "BEBAN MATERIAL, PERALATAN DAN ANGKUTAN", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "510000", accountLevel: AccountLevel.CLUSTER },
	{ id: "513000", description: "BEBAN ADMINISTRASI DAN UMUM", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "510000", accountLevel: AccountLevel.CLUSTER },
	{ id: "631000", description: "PERALATAN KERJA", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "630000", accountLevel: AccountLevel.CLUSTER },
	{ id: "632000", description: "PERLENGKAPAN KANTOR", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "630000", accountLevel: AccountLevel.CLUSTER },
	{ id: "633000", description: "KENDARAAN", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "630000", accountLevel: AccountLevel.CLUSTER },
	{ id: "634000", description: "PERLENGKAPAN GEDUNG DAN BANGUNAN", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "630000", accountLevel: AccountLevel.CLUSTER },
	{ id: "635000", description: "GEDUNG DAN BANGUNAN", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "630000", accountLevel: AccountLevel.CLUSTER },
	{ id: "641000", description: "BEBAN PENYUSUTAN ASET TETAP", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "640000", accountLevel: AccountLevel.CLUSTER },
	{ id: "642000", description: "BEBAN AMORTISASI", levelAcc:3, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "640000", accountLevel: AccountLevel.CLUSTER },

	// Level 4
	{ id: "111100", description: "UANG TUNAI", levelAcc:4, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "111000", accountLevel: AccountLevel.SUB_CLUSTER, showInReport: false, cashAccount: true },
	{ id: "111200", description: "REKENING TABUNGAN", levelAcc:4, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "111000", accountLevel: AccountLevel.SUB_CLUSTER, showInReport: false, cashAccount: true },
	{ id: "111300", description: "REKENING GIRO", levelAcc:4, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "111000", accountLevel: AccountLevel.SUB_CLUSTER, showInReport: false, cashAccount: true },
	// { id: "111100", description: "UANG TUNAI", levelAcc:4, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "111000", accountLevel: AccountLevel.SUB_CLUSTER, showInReport: false, cashAccount: true },
	{ id: "112100", description: "PIUTANG USAHA", levelAcc:4, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "112000", accountLevel: AccountLevel.SUB_CLUSTER, showInReport: true },
	{ id: "112200", description: "PIUTANG LAIN LAIN", levelAcc:4, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "112000", accountLevel: AccountLevel.SUB_CLUSTER, showInReport: true },
	{ id: "112300", description: "PENYISIHAN PIUTANG", levelAcc:4, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "112000", accountLevel: AccountLevel.SUB_CLUSTER, showInReport: true },
	// { id: "112300", description: "PENYISIHAN", levelAcc:4, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "112000", accountLevel: AccountLevel.SUB_CLUSTER, showInReport: true },
	{ id: "121100", description: "HARGA PEROLEHAN - ASET TETAP", levelAcc:4, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "121000", accountLevel: AccountLevel.SUB_CLUSTER, showInReport: true },
	{ id: "121200", description: "AKUMULASI PENYUSUTAN - ASET TETAP", levelAcc:4, typeAcc: GroupAccount.GROUP, isDebit: false, parentId: "121000", accountLevel: AccountLevel.SUB_CLUSTER, showInReport: true },

	{ id: "124100", description: "AKTIVA TETAP TIDAK BEROPERASI", levelAcc:4, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "124000", accountLevel: AccountLevel.SUB_CLUSTER},

	// Level 5
	{ id: "112110", description: "PIUTANG USAHA-PENETAPAN", levelAcc:5, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "112100", accountLevel: AccountLevel.UNIT_CLUSTER },
	{ id: "112120", description: "PIUTANG USAHA-DITAGIH", levelAcc:5, typeAcc: GroupAccount.GROUP, isDebit: true, parentId: "112100", accountLevel: AccountLevel.UNIT_CLUSTER },

	// Level 6
	{ id: "111101", description: "Kas", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "111100", accountLevel: AccountLevel.DETAIL, cashAccount: true },
  { id: "111102", description: "Kas kecil", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "111100", accountLevel: AccountLevel.DETAIL, cashAccount: true },
  { id: "111201", description: "Bank BNI - Tabungan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "111200", accountLevel: AccountLevel.DETAIL, cashAccount: true },
  { id: "111202", description: "Bank Mandiri - Tabungan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "111200", accountLevel: AccountLevel.DETAIL, cashAccount: true },
  { id: "111203", description: "Bank BRI - Tabungan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "111200", accountLevel: AccountLevel.DETAIL, cashAccount: true },
  { id: "111301", description: "Bank BNI - Giro", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "111300", accountLevel: AccountLevel.DETAIL, cashAccount: true },
  { id: "111302", description: "Bank Mandiri - Giro", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "111300", accountLevel: AccountLevel.DETAIL, cashAccount: true },
  { id: "111303", description: "Bank BRI - Giro Penerimaan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "111300", accountLevel: AccountLevel.DETAIL, cashAccount: true },
  { id: "111304", description: "Bank BRI - Giro Pembiayaan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "111300", accountLevel: AccountLevel.DETAIL, cashAccount: true },

	{ id: "112111", description: "Piutang Penetapan Jasa Alih Daya", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "112110", accountLevel: AccountLevel.DETAIL },
  { id: "112112", description: "Piutang Penetapan Pekerjaan Tehnik", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "112110", accountLevel: AccountLevel.DETAIL },
  { id: "112113", description: "Piutang Penetapan Pengadaan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "112110", accountLevel: AccountLevel.DETAIL },
	{ id: "112121", description: "Piutang Ditagih Jasa Alih Daya", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "112120", accountLevel: AccountLevel.DETAIL },
	{ id: "112122", description: "Piutang Ditagih Pekerjaan Tehnik", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "112120", accountLevel: AccountLevel.DETAIL },
	{ id: "112123", description: "Piutang Ditagih Pengadaan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "112120", accountLevel: AccountLevel.DETAIL },
  // { id: "112108", description: "Piutang Ragu Ragu", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "112100" , accountLevel: AccountLevel.DETAIL },

  { id: "112201", description: "Piutang Rupa Rupa Klaim", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "112200" , accountLevel: AccountLevel.DETAIL },
  { id: "112202", description: "Piutang Ragu Ragu", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "112200" , accountLevel: AccountLevel.DETAIL },
  { id: "112203", description: "Piutang Pihak Berelasi", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "112200" , accountLevel: AccountLevel.DETAIL },

  { id: "112301", description: "Penyisihan Piutang", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "112300" , accountLevel: AccountLevel.DETAIL },

  { id: "113001", description: "Persediaan Bahan Bakar dan Minyak", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "113000" , accountLevel: AccountLevel.DETAIL },
  { id: "113002", description: "Persediaan Material", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "113000" , accountLevel: AccountLevel.DETAIL },
  { id: "113003", description: "Persediaan Barang Dijual", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "113000" , accountLevel: AccountLevel.DETAIL },
  { id: "113004", description: "Selisih Persediaan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "113000" , accountLevel: AccountLevel.DETAIL },

  { id: "114001", description: "Uang Muka Pembelian", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "114000" , accountLevel: AccountLevel.DETAIL },
  { id: "114002", description: "Beban Dibayar Dimuka", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "114000" , accountLevel: AccountLevel.DETAIL },
  { id: "114003", description: "Beban Ditangguhkan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "114000" , accountLevel: AccountLevel.DETAIL },
  { id: "114004", description: "Uang Muka Dividen", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "114000" , accountLevel: AccountLevel.DETAIL },

  { id: "115001", description: "Pajak PPh Pasal 22", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "115000" , accountLevel: AccountLevel.DETAIL },
  { id: "115002", description: "Pajak PPh Pasal 23", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "115000" , accountLevel: AccountLevel.DETAIL },
  { id: "115003", description: "Pajak PPh Pasal 25", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "115000" , accountLevel: AccountLevel.DETAIL },
  { id: "115004", description: "Pajak Pertambahan Nilai", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "115000" , accountLevel: AccountLevel.DETAIL },

	{ id: "121101", description: "Peralatan Kerja", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "121100", accountLevel: AccountLevel.DETAIL },
  { id: "121102", description: "Perlengkapan kantor", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "121100", accountLevel: AccountLevel.DETAIL },
  { id: "121103", description: "Kendaraan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "121100", accountLevel: AccountLevel.DETAIL },
  { id: "121104", description: "Perlengkapan Gedung dan Bangunan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "121100", accountLevel: AccountLevel.DETAIL },
  { id: "121105", description: "Gedung dan Bangunan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "121100", accountLevel: AccountLevel.DETAIL },
  { id: "121106", description: "Tanah", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "121100", accountLevel: AccountLevel.DETAIL },
	{ id: "121201", description: "Akumulasi penyusutan Peralatan Kerja", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "121200", accountLevel: AccountLevel.DETAIL },
  { id: "121202", description: "Akumulasi penyusutan Perlengkapan kantor", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "121200", accountLevel: AccountLevel.DETAIL },
  { id: "121203", description: "Akumulasi penyusutan Kendaraan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "121200", accountLevel: AccountLevel.DETAIL },
  { id: "121204", description: "Akumulasi penyusutan Perlengkapan Gedung dan Bangunan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "121200", accountLevel: AccountLevel.DETAIL },
  { id: "121205", description: "Akumulasi penyusutan Gedung dan Bangunan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "121200", accountLevel: AccountLevel.DETAIL },

	{ id: "122001", description: "Uang Muka Pembelian", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "122000", accountLevel: AccountLevel.DETAIL },
  { id: "122002", description: "Beban Dibayar Dimuka", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "122000", accountLevel: AccountLevel.DETAIL },
  { id: "122003", description: "Beban Ditangguhkan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "122000", accountLevel: AccountLevel.DETAIL },

	{ id: "123001", description: "Investasi Pada Property", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "123000", accountLevel: AccountLevel.DETAIL },
  { id: "123002", description: "Investasi pada Franchise", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "123000", accountLevel: AccountLevel.DETAIL },
  { id: "123003", description: "Investasi pada Penyertaan Modal", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "123000", accountLevel: AccountLevel.DETAIL },

	{ id: "124101", description: "Perolehan Aktiva Tetap Tidak Beroperasi", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "124100", accountLevel: AccountLevel.DETAIL },
  { id: "124102", description: "Akumulasi Penyusutan Aktiva Tetap Tidak Beroperasi", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "124100", accountLevel: AccountLevel.DETAIL },

	{ id: "190001", description: "Pos Silang", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "190000", accountLevel: AccountLevel.DETAIL },

	{ id: "211001", description: "Utang Pengadaan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "211000", accountLevel: AccountLevel.DETAIL },
  { id: "211002", description: "Utang Sewa", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "211000", accountLevel: AccountLevel.DETAIL },
  { id: "211009", description: "Utang Usaha Lainnya", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "211000", accountLevel: AccountLevel.DETAIL },

	{ id: "212001", description: "Utang Bank", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "212000", accountLevel: AccountLevel.DETAIL },
  { id: "212002", description: "Utang Koperasi", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "212000", accountLevel: AccountLevel.DETAIL },
  { id: "212003", description: "Utang Lembaga Keuangan Lainnya", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "212000", accountLevel: AccountLevel.DETAIL },

  { id: "213001", description: "Utang PPh Pasal 21", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "213000", accountLevel: AccountLevel.DETAIL },
  { id: "213002", description: "Utang PPh Pasal 21", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "213000", accountLevel: AccountLevel.DETAIL },
  { id: "213003", description: "Utang PPh Final", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "213000", accountLevel: AccountLevel.DETAIL },
  { id: "213004", description: "Utang PPh Badan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "213000", accountLevel: AccountLevel.DETAIL },
  { id: "213005", description: "Utang PPn", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "213000", accountLevel: AccountLevel.DETAIL },

	{ id: "214001", description: "Beban Yang Masih Harus Dibayar", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "214000", accountLevel: AccountLevel.DETAIL },
  { id: "214002", description: "Deviden Yang Masih Harus Dibayar", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "214000", accountLevel: AccountLevel.DETAIL },

	{ id: "220001", description: "Utang Bank", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "220000", accountLevel: AccountLevel.DETAIL },
  { id: "220002", description: "Utang Pada Koperasi", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "220000", accountLevel: AccountLevel.DETAIL },
  { id: "220009", description: "Utang Jangka Panjang Lainnya", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "220000", accountLevel: AccountLevel.DETAIL },

	{ id: "310001", description: "Modal Ditempatkan dan Disetor Penuh", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "310000", accountLevel: AccountLevel.DETAIL, showInReport: true },
  { id: "320001", description: "Laba Belum Ditentukan Penggunaanya", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "320000", accountLevel: AccountLevel.DETAIL, showInReport: true },
  { id: "320002", description: "Cadangan Laba", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "320000", accountLevel: AccountLevel.DETAIL, showInReport: true },
  { id: "320003", description: "Laba Tahun Berjalan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "320000", accountLevel: AccountLevel.DETAIL, showInReport: true },
  { id: "320004", description: "Laba Bulan Berjalan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "320000", accountLevel: AccountLevel.DETAIL, showInReport: true },
  //{ id: "330001", description: "Ikhtisar Laba-Rugi", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "330000", accountLevel: AccountLevel.DETAIL },



	{ id: "400001", description: "Jasa Tenaga Kerja Alih Daya", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "400000", accountLevel: AccountLevel.DETAIL, showInReport: true },
  { id: "400002", description: "Jasa Konstruksi Dan Pemeliharaan Kelistrikan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "400000", accountLevel: AccountLevel.DETAIL, showInReport: true },
  { id: "400003", description: "Jasa Lainnya", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "400000", accountLevel: AccountLevel.DETAIL, showInReport: true },
  { id: "400004", description: "Pengadaan Barang", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "400000", accountLevel: AccountLevel.DETAIL, showInReport: true },

	{ id: "511001", description: "Beban gaji / Upah", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "511000", accountLevel: AccountLevel.DETAIL },
	{ id: "511002", description: "Beban Tujangan Hari Raya", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "511000", accountLevel: AccountLevel.DETAIL },
	{ id: "511003", description: "Beban Premi Asuransi", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "511000", accountLevel: AccountLevel.DETAIL },
	{ id: "511004", description: "Beban Pakaian", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "511000", accountLevel: AccountLevel.DETAIL },
	{ id: "511005", description: "Beban Pendidikan & Latihan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "511000", accountLevel: AccountLevel.DETAIL },
	{ id: "512001", description: "Beban Material", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "512000", accountLevel: AccountLevel.DETAIL },
	{ id: "512002", description: "Beban Alat Kerja", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "512000", accountLevel: AccountLevel.DETAIL },
	{ id: "512003", description: "Beban Kendaraan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "512000", accountLevel: AccountLevel.DETAIL },
	{ id: "512004", description: "Beban BBM ", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "512000", accountLevel: AccountLevel.DETAIL },
	{ id: "513001", description: "Beban Telpon", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "513000", accountLevel: AccountLevel.DETAIL },
	{ id: "513002", description: "Beban Konsumsi", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "513000", accountLevel: AccountLevel.DETAIL },
	{ id: "513003", description: "Beban Administrasi dan Umum", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "513000", accountLevel: AccountLevel.DETAIL },

	{ id: "520001", description: "Jasa Treatmen Oil dan Pemeliharaan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "520000", accountLevel: AccountLevel.DETAIL },
	{ id: "520002", description: "Jasa Treatmen Oil dan Pemeliharaan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "520000", accountLevel: AccountLevel.DETAIL },
	{ id: "520003", description: "Beban Material", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "520000", accountLevel: AccountLevel.DETAIL },
	{ id: "520004", description: "Beban Alat Kerja", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "520000", accountLevel: AccountLevel.DETAIL },
	{ id: "520005", description: "Beban Kendaraan dan BBM", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "520000", accountLevel: AccountLevel.DETAIL },
	{ id: "520006", description: "Beban Konsumsi", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "520000", accountLevel: AccountLevel.DETAIL },

	{ id: "530001", description: "Beban Tenaga Kerja", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "530000", accountLevel: AccountLevel.DETAIL },
	{ id: "530002", description: "Beban Material", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "530000", accountLevel: AccountLevel.DETAIL },
	{ id: "530003", description: "Beban Alat Kerja", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "530000", accountLevel: AccountLevel.DETAIL },
	{ id: "530004", description: "Beban Kendaraan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "530000", accountLevel: AccountLevel.DETAIL },
	{ id: "530005", description: "Beban BBM ", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "530000", accountLevel: AccountLevel.DETAIL },
	{ id: "530006", description: "Beban Telpon", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "530000", accountLevel: AccountLevel.DETAIL },
	{ id: "530007", description: "Beban Konsumsi", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "530000", accountLevel: AccountLevel.DETAIL },
	{ id: "530008", description: "Beban Administrasi dan Umum", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "530000", accountLevel: AccountLevel.DETAIL },
	{ id: "580001", description: "Harga Pokok Pengadaan Barang.", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "580000", accountLevel: AccountLevel.DETAIL },

	{ id: "610001", description: "Gaji/Upah Pokok", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "610000", accountLevel: AccountLevel.DETAIL },
	{ id: "610002", description: "Tunjangan Tetap", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "610000", accountLevel: AccountLevel.DETAIL },
	{ id: "610003", description: "Tunjangan Kinerja", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "610000", accountLevel: AccountLevel.DETAIL },
	{ id: "610004", description: "Tunjangan Transportasi/Kehadiran", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "610000", accountLevel: AccountLevel.DETAIL },
	{ id: "610005", description: "Tunjangan Makan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "610000", accountLevel: AccountLevel.DETAIL },
	{ id: "610006", description: "Uang Lembur", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "610000", accountLevel: AccountLevel.DETAIL },
	{ id: "610007", description: "Honorarium", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "610000", accountLevel: AccountLevel.DETAIL },
	{ id: "610008", description: "Beban Asuransi", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "610000", accountLevel: AccountLevel.DETAIL },
	{ id: "610009", description: "Tunjangan Hari Raya", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "610000", accountLevel: AccountLevel.DETAIL },
	{ id: "610010", description: "Bonus/Intensif", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "610000", accountLevel: AccountLevel.DETAIL },
	{ id: "610011", description: "Pakaian Dinas", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "610000", accountLevel: AccountLevel.DETAIL },
	{ id: "610012", description: "Beban Pajak", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "610000", accountLevel: AccountLevel.DETAIL },

	{ id: "620001", description: "Beban Alat Tulis Kantor", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },
	{ id: "620002", description: "Beban Percetakan, Penjilidan Dan Penggandaan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },
	{ id: "620003", description: "Beban Meterai", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },
	{ id: "620004", description: "Beban Koran", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },
	{ id: "620005", description: "Beban Pengiriman Dokumen", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },
	{ id: "620006", description: "Beban Kebersihan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },
	{ id: "620007", description: "Beban Keamanan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },
	{ id: "620008", description: "Beban Listrik dan Air", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },
	{ id: "620009", description: "Beban Telepon dan Jaringan Komunikasi", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },
	{ id: "620010", description: "Beban Konsumsi", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },
	{ id: "620011", description: "Beban Perijinan dan Tender", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },
	{ id: "620012", description: "Beban Audit dan Konsultan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },
	{ id: "620013", description: "Beban Penggunaan Aplikasi", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },
	{ id: "620014", description: "Beban Perijinan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },
	{ id: "620015", description: "Beban Tender Dan Jaminan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },
	{ id: "620016", description: "Beban Beban Beban Sewa", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },
	{ id: "620017", description: "Beban Perjalanan Dinas", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },
	{ id: "620018", description: "Beban Transportasi dan Pengangkutan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },
	{ id: "620019", description: "Beban BBM", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "620000", accountLevel: AccountLevel.DETAIL },

	{ id: "631001", description: "Jasa Pemeliharaan - Peralatan Kerja", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "631000", accountLevel: AccountLevel.DETAIL },
	{ id: "631002", description: "Material  Pemeliharaan - Peralatan Kerja", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "631000", accountLevel: AccountLevel.DETAIL },
	{ id: "632001", description: "Jasa Pemeliharaan - Perlengkapan Kantor", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "632000", accountLevel: AccountLevel.DETAIL },
	{ id: "632002", description: "Material Pemeliharaan - Perlengkapan Kantor", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "632000", accountLevel: AccountLevel.DETAIL },
	{ id: "633001", description: "Jasa Pemeliharaan - Kendaraan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "633000", accountLevel: AccountLevel.DETAIL },
	{ id: "633002", description: "Material Pemeliharaan - Kendaraan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "633000", accountLevel: AccountLevel.DETAIL },
	{ id: "634001", description: "Jasa Pemeliharaan - Perlengkapan Gedung dan Bangunan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "634000", accountLevel: AccountLevel.DETAIL },
	{ id: "634002", description: "Material Pemeliharaan - Perlengkapan Gedung dan Bangunan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "634000", accountLevel: AccountLevel.DETAIL },
	{ id: "635001", description: "Jasa Pemeliharaan - Gedung dan Bangunan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "635000", accountLevel: AccountLevel.DETAIL },
	{ id: "635002", description: "Material Pemeliharaan - Gedung dan Bangunan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "635000", accountLevel: AccountLevel.DETAIL },

	{ id: "641001", description: "Beban Penyusutan - Peralatan Kerja", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "641000", accountLevel: AccountLevel.DETAIL },
	{ id: "641002", description: "Beban Penyusutan - Perlengkapan Kantor", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "641000", accountLevel: AccountLevel.DETAIL },
	{ id: "641003", description: "Beban Penyusutan - Kendaraan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "641000", accountLevel: AccountLevel.DETAIL },
	{ id: "641004", description: "Beban Penyusutan - Gedung dan Bangunan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "641000", accountLevel: AccountLevel.DETAIL },
	{ id: "641005", description: "Beban Penyusutan - Perlengkapan Gedung dan Bangunan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "641000", accountLevel: AccountLevel.DETAIL },

	{ id: "642001", description: "Beban Amortisasi", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "642000", accountLevel: AccountLevel.DETAIL },

	{ id: "710001", description: "Pendapatan Bunga Bank", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "710000", accountLevel: AccountLevel.DETAIL },
	{ id: "710002", description: "Pendapatan Penjualan Aset Eks Tarikan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "710000", accountLevel: AccountLevel.DETAIL },
	{ id: "710003", description: "Koreksi Beban Tahun Lalu", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "710000", accountLevel: AccountLevel.DETAIL },
	{ id: "710009", description: "Pendapatan Diluar Operasi Lainnya", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: false, parentId: "710000", accountLevel: AccountLevel.DETAIL },

	{ id: "720001", description: "Beban Administrasi Bank", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "720000", accountLevel: AccountLevel.DETAIL },
	{ id: "720002", description: "Beban Pajak Atas Bunga", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "720000", accountLevel: AccountLevel.DETAIL },
	{ id: "720003", description: "Bantuan Pengembangan Lingkungan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "720000", accountLevel: AccountLevel.DETAIL },
	{ id: "720004", description: "Sumbangan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "720000", accountLevel: AccountLevel.DETAIL },
	{ id: "720005", description: "Beban Penyusutan Aset Dipercepat", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "720000", accountLevel: AccountLevel.DETAIL },
	{ id: "720006", description: "Rugi Penarikan Aset", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "720000", accountLevel: AccountLevel.DETAIL },
	{ id: "720007", description: "Koreksi Pendapatan Tahun Lalu", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "720000", accountLevel: AccountLevel.DETAIL },
	{ id: "720008", description: "Beban Selisih selisih", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "720000", accountLevel: AccountLevel.DETAIL },
	{ id: "720009", description: "Beban Beban Denda", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "720000", accountLevel: AccountLevel.DETAIL },
	{ id: "720019", description: "Beban Diluar Operasi Lainnya", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "720000", accountLevel: AccountLevel.DETAIL },

	{ id: "800001", description: "Pajak Penghasilan Badan", levelAcc:6, typeAcc: GroupAccount.DETAIL, isDebit: true, parentId: "800000", accountLevel: AccountLevel.DETAIL },

]; */
